// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api.proto

#include "api.pb.h"
#include "api.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* EmployeeService_method_names[] = {
  "/EmployeeService/AddEmployee",
  "/EmployeeService/DeleteEmployee",
  "/EmployeeService/UpdateEmployee",
  "/EmployeeService/GetEmployee",
  "/EmployeeService/GetEmployeeByKeyword",
  "/EmployeeService/StatisticByDepartment",
  "/EmployeeService/StatisticByEducation",
  "/EmployeeService/Test",
};

std::unique_ptr< EmployeeService::Stub> EmployeeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< EmployeeService::Stub> stub(new EmployeeService::Stub(channel, options));
  return stub;
}

EmployeeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AddEmployee_(EmployeeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteEmployee_(EmployeeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateEmployee_(EmployeeService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetEmployee_(EmployeeService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetEmployeeByKeyword_(EmployeeService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StatisticByDepartment_(EmployeeService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StatisticByEducation_(EmployeeService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Test_(EmployeeService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status EmployeeService::Stub::AddEmployee(::grpc::ClientContext* context, const ::AddEmployeeRequest& request, ::AddEmployeeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AddEmployeeRequest, ::AddEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddEmployee_, context, request, response);
}

void EmployeeService::Stub::async::AddEmployee(::grpc::ClientContext* context, const ::AddEmployeeRequest* request, ::AddEmployeeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AddEmployeeRequest, ::AddEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddEmployee_, context, request, response, std::move(f));
}

void EmployeeService::Stub::async::AddEmployee(::grpc::ClientContext* context, const ::AddEmployeeRequest* request, ::AddEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddEmployee_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AddEmployeeResponse>* EmployeeService::Stub::PrepareAsyncAddEmployeeRaw(::grpc::ClientContext* context, const ::AddEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AddEmployeeResponse, ::AddEmployeeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddEmployee_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AddEmployeeResponse>* EmployeeService::Stub::AsyncAddEmployeeRaw(::grpc::ClientContext* context, const ::AddEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddEmployeeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EmployeeService::Stub::DeleteEmployee(::grpc::ClientContext* context, const ::DeleteEmployeeRequest& request, ::DeleteEmployeeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::DeleteEmployeeRequest, ::DeleteEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteEmployee_, context, request, response);
}

void EmployeeService::Stub::async::DeleteEmployee(::grpc::ClientContext* context, const ::DeleteEmployeeRequest* request, ::DeleteEmployeeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::DeleteEmployeeRequest, ::DeleteEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteEmployee_, context, request, response, std::move(f));
}

void EmployeeService::Stub::async::DeleteEmployee(::grpc::ClientContext* context, const ::DeleteEmployeeRequest* request, ::DeleteEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteEmployee_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DeleteEmployeeResponse>* EmployeeService::Stub::PrepareAsyncDeleteEmployeeRaw(::grpc::ClientContext* context, const ::DeleteEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::DeleteEmployeeResponse, ::DeleteEmployeeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteEmployee_, context, request);
}

::grpc::ClientAsyncResponseReader< ::DeleteEmployeeResponse>* EmployeeService::Stub::AsyncDeleteEmployeeRaw(::grpc::ClientContext* context, const ::DeleteEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteEmployeeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EmployeeService::Stub::UpdateEmployee(::grpc::ClientContext* context, const ::UpdateEmployeeRequest& request, ::UpdateEmployeeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::UpdateEmployeeRequest, ::UpdateEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateEmployee_, context, request, response);
}

void EmployeeService::Stub::async::UpdateEmployee(::grpc::ClientContext* context, const ::UpdateEmployeeRequest* request, ::UpdateEmployeeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::UpdateEmployeeRequest, ::UpdateEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateEmployee_, context, request, response, std::move(f));
}

void EmployeeService::Stub::async::UpdateEmployee(::grpc::ClientContext* context, const ::UpdateEmployeeRequest* request, ::UpdateEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateEmployee_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::UpdateEmployeeResponse>* EmployeeService::Stub::PrepareAsyncUpdateEmployeeRaw(::grpc::ClientContext* context, const ::UpdateEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::UpdateEmployeeResponse, ::UpdateEmployeeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateEmployee_, context, request);
}

::grpc::ClientAsyncResponseReader< ::UpdateEmployeeResponse>* EmployeeService::Stub::AsyncUpdateEmployeeRaw(::grpc::ClientContext* context, const ::UpdateEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateEmployeeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EmployeeService::Stub::GetEmployee(::grpc::ClientContext* context, const ::GetEmployeeRequest& request, ::GetEmployeeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GetEmployeeRequest, ::GetEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetEmployee_, context, request, response);
}

void EmployeeService::Stub::async::GetEmployee(::grpc::ClientContext* context, const ::GetEmployeeRequest* request, ::GetEmployeeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GetEmployeeRequest, ::GetEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetEmployee_, context, request, response, std::move(f));
}

void EmployeeService::Stub::async::GetEmployee(::grpc::ClientContext* context, const ::GetEmployeeRequest* request, ::GetEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetEmployee_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GetEmployeeResponse>* EmployeeService::Stub::PrepareAsyncGetEmployeeRaw(::grpc::ClientContext* context, const ::GetEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GetEmployeeResponse, ::GetEmployeeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetEmployee_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GetEmployeeResponse>* EmployeeService::Stub::AsyncGetEmployeeRaw(::grpc::ClientContext* context, const ::GetEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetEmployeeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EmployeeService::Stub::GetEmployeeByKeyword(::grpc::ClientContext* context, const ::GetEmployeeByKeywordRequest& request, ::GetEmployeeByKeywordResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GetEmployeeByKeywordRequest, ::GetEmployeeByKeywordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetEmployeeByKeyword_, context, request, response);
}

void EmployeeService::Stub::async::GetEmployeeByKeyword(::grpc::ClientContext* context, const ::GetEmployeeByKeywordRequest* request, ::GetEmployeeByKeywordResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GetEmployeeByKeywordRequest, ::GetEmployeeByKeywordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetEmployeeByKeyword_, context, request, response, std::move(f));
}

void EmployeeService::Stub::async::GetEmployeeByKeyword(::grpc::ClientContext* context, const ::GetEmployeeByKeywordRequest* request, ::GetEmployeeByKeywordResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetEmployeeByKeyword_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GetEmployeeByKeywordResponse>* EmployeeService::Stub::PrepareAsyncGetEmployeeByKeywordRaw(::grpc::ClientContext* context, const ::GetEmployeeByKeywordRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GetEmployeeByKeywordResponse, ::GetEmployeeByKeywordRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetEmployeeByKeyword_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GetEmployeeByKeywordResponse>* EmployeeService::Stub::AsyncGetEmployeeByKeywordRaw(::grpc::ClientContext* context, const ::GetEmployeeByKeywordRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetEmployeeByKeywordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EmployeeService::Stub::StatisticByDepartment(::grpc::ClientContext* context, const ::StatisticByDepartmentRequest& request, ::StatisticByDepartmentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::StatisticByDepartmentRequest, ::StatisticByDepartmentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StatisticByDepartment_, context, request, response);
}

void EmployeeService::Stub::async::StatisticByDepartment(::grpc::ClientContext* context, const ::StatisticByDepartmentRequest* request, ::StatisticByDepartmentResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::StatisticByDepartmentRequest, ::StatisticByDepartmentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StatisticByDepartment_, context, request, response, std::move(f));
}

void EmployeeService::Stub::async::StatisticByDepartment(::grpc::ClientContext* context, const ::StatisticByDepartmentRequest* request, ::StatisticByDepartmentResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StatisticByDepartment_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StatisticByDepartmentResponse>* EmployeeService::Stub::PrepareAsyncStatisticByDepartmentRaw(::grpc::ClientContext* context, const ::StatisticByDepartmentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StatisticByDepartmentResponse, ::StatisticByDepartmentRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StatisticByDepartment_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StatisticByDepartmentResponse>* EmployeeService::Stub::AsyncStatisticByDepartmentRaw(::grpc::ClientContext* context, const ::StatisticByDepartmentRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStatisticByDepartmentRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EmployeeService::Stub::StatisticByEducation(::grpc::ClientContext* context, const ::StatisticByEducationRequest& request, ::StatisticByEducationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::StatisticByEducationRequest, ::StatisticByEducationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StatisticByEducation_, context, request, response);
}

void EmployeeService::Stub::async::StatisticByEducation(::grpc::ClientContext* context, const ::StatisticByEducationRequest* request, ::StatisticByEducationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::StatisticByEducationRequest, ::StatisticByEducationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StatisticByEducation_, context, request, response, std::move(f));
}

void EmployeeService::Stub::async::StatisticByEducation(::grpc::ClientContext* context, const ::StatisticByEducationRequest* request, ::StatisticByEducationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StatisticByEducation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StatisticByEducationResponse>* EmployeeService::Stub::PrepareAsyncStatisticByEducationRaw(::grpc::ClientContext* context, const ::StatisticByEducationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StatisticByEducationResponse, ::StatisticByEducationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StatisticByEducation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StatisticByEducationResponse>* EmployeeService::Stub::AsyncStatisticByEducationRaw(::grpc::ClientContext* context, const ::StatisticByEducationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStatisticByEducationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EmployeeService::Stub::Test(::grpc::ClientContext* context, const ::TestRequest& request, ::TestResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TestRequest, ::TestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Test_, context, request, response);
}

void EmployeeService::Stub::async::Test(::grpc::ClientContext* context, const ::TestRequest* request, ::TestResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TestRequest, ::TestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Test_, context, request, response, std::move(f));
}

void EmployeeService::Stub::async::Test(::grpc::ClientContext* context, const ::TestRequest* request, ::TestResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Test_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TestResponse>* EmployeeService::Stub::PrepareAsyncTestRaw(::grpc::ClientContext* context, const ::TestRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TestResponse, ::TestRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Test_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TestResponse>* EmployeeService::Stub::AsyncTestRaw(::grpc::ClientContext* context, const ::TestRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTestRaw(context, request, cq);
  result->StartCall();
  return result;
}

EmployeeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EmployeeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EmployeeService::Service, ::AddEmployeeRequest, ::AddEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EmployeeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AddEmployeeRequest* req,
             ::AddEmployeeResponse* resp) {
               return service->AddEmployee(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EmployeeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EmployeeService::Service, ::DeleteEmployeeRequest, ::DeleteEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EmployeeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::DeleteEmployeeRequest* req,
             ::DeleteEmployeeResponse* resp) {
               return service->DeleteEmployee(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EmployeeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EmployeeService::Service, ::UpdateEmployeeRequest, ::UpdateEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EmployeeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::UpdateEmployeeRequest* req,
             ::UpdateEmployeeResponse* resp) {
               return service->UpdateEmployee(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EmployeeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EmployeeService::Service, ::GetEmployeeRequest, ::GetEmployeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EmployeeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GetEmployeeRequest* req,
             ::GetEmployeeResponse* resp) {
               return service->GetEmployee(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EmployeeService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EmployeeService::Service, ::GetEmployeeByKeywordRequest, ::GetEmployeeByKeywordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EmployeeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GetEmployeeByKeywordRequest* req,
             ::GetEmployeeByKeywordResponse* resp) {
               return service->GetEmployeeByKeyword(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EmployeeService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EmployeeService::Service, ::StatisticByDepartmentRequest, ::StatisticByDepartmentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EmployeeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::StatisticByDepartmentRequest* req,
             ::StatisticByDepartmentResponse* resp) {
               return service->StatisticByDepartment(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EmployeeService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EmployeeService::Service, ::StatisticByEducationRequest, ::StatisticByEducationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EmployeeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::StatisticByEducationRequest* req,
             ::StatisticByEducationResponse* resp) {
               return service->StatisticByEducation(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EmployeeService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EmployeeService::Service, ::TestRequest, ::TestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EmployeeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TestRequest* req,
             ::TestResponse* resp) {
               return service->Test(ctx, req, resp);
             }, this)));
}

EmployeeService::Service::~Service() {
}

::grpc::Status EmployeeService::Service::AddEmployee(::grpc::ServerContext* context, const ::AddEmployeeRequest* request, ::AddEmployeeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EmployeeService::Service::DeleteEmployee(::grpc::ServerContext* context, const ::DeleteEmployeeRequest* request, ::DeleteEmployeeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EmployeeService::Service::UpdateEmployee(::grpc::ServerContext* context, const ::UpdateEmployeeRequest* request, ::UpdateEmployeeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EmployeeService::Service::GetEmployee(::grpc::ServerContext* context, const ::GetEmployeeRequest* request, ::GetEmployeeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EmployeeService::Service::GetEmployeeByKeyword(::grpc::ServerContext* context, const ::GetEmployeeByKeywordRequest* request, ::GetEmployeeByKeywordResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EmployeeService::Service::StatisticByDepartment(::grpc::ServerContext* context, const ::StatisticByDepartmentRequest* request, ::StatisticByDepartmentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EmployeeService::Service::StatisticByEducation(::grpc::ServerContext* context, const ::StatisticByEducationRequest* request, ::StatisticByEducationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EmployeeService::Service::Test(::grpc::ServerContext* context, const ::TestRequest* request, ::TestResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


