cc_library (
  name = "api",
  srcs = [
    "api.pb.cc",
    "api.grpc.pb.cc",
  ],
  hdrs = [
    "api.pb.h",
    "api.grpc.pb.h",
  ],
  deps = [
    "@com_github_grpc_grpc//:grpc++",
  ],
  visibility = ["//src:__pkg__"],
)
